### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by ghost** [Biitez/Authenty-ME#2]
Hey!

I was browsing through this repository and noticed that you can improve a few things with your project that would improve maintainability and other aspects.

- Split your request controller, HWID class and other things to seperate files. This will greatly increase maintainability 
- Throw more specific exceptions, I noticed you were throwing generic exceptions on null checks, when you could be using ArgumentNullException instead
- Since you're using Newtonsoft.Json, you can switch some of your models from classes to structs - this will actually improve speed quite a fair bit since you have quite a lot of models.
- Make some asynchronous methods, I noticed you're using HttpClient (which is great) but you're also using GetAwaiter and GetResult.

 
I also noticed some potential issues with your service as a whole.

- You're using AES-256 to encrypt messages to & from your API, this is just unnecessary as HTTPS does this for you. Removing that will actually increase speed a whole lot and would also reduce your server load.
- You could (not really necessary but would be nice) switch your API request payloads to use JSON instead (application/json).

**Comment by biitez** [comment]
Hi, thank you very much for taking the time to review my project and give me tips to improve it,

Regarding the first 4 aspects you gave me, you are absolutely right, it is something I have had in mind for a while, so, lately I have been working on a library made in netstandard where I improve at least, most of the problems that this class contains, and also with new functionalities that are not published in the panel and in the current class.

(There are still quite a few changes I want to make before publishing it, including new APIs and ways to make it secure without breaking the users' program).

I use an encryption to communicate with the API because even if the requests are under HTTPS and the SSL is pinned to a public key of the certificate, there are possibilities to cheat the program with a different response (to 'skip' the login). I know there are several ways to protect it that are much more optimal, but for me, the most secure was this, encrypting AES keys under a unique RSA for each application, also I have been working on the server to make the response speed faster and optimal.

Also, I will stop using the Newtonsoft.Json library, the new library will use only native visual studio references, the server side responses will be handled in a different way.

I really appreciate your tips and will keep it in mind as I continue to work on this project.
